module.exports = {
    "A92":"Ardee",	
    "Y14":"Arklow",	
    "A84":"Ashbourne",	
    "H65":"Athenry",	
    "N37":"Athlone",	
    "R14":"Athy",	
    "K32":"Balbriggan",	
    "F26":"Ballina",	
    "H53":"Ballinasloe",	
    "P31":"Ballincollig",	
    "F31":"Ballinrobe",	
    "A75":"Ballybay",	
    "A41":"Ballyboughal",	
    "F35":"Ballyhaunis",	
    "F56":"Ballymote",	
    "P72":"Bandon",	
    "P75":"Bantry",	
    "H14":"Belturbet",	
    "R42":"Birr",	
    "A94":"Blackrock, Booterstown",	
    "F52":"Boyle",	
    "A98":"Bray",	
    "V23":"Caherciveen",	
    "E21":"Cahir",	
    "R93":"Carlow",	
    "A81":"Carrickmacross",	
    "N41":"Carrick-on-Shannon",	
    "E32":"Carrick-on-Suir",	
    "P43":"Carrigaline",	
    "E25":"Cashel",	
    "F23":"Castlebar",	
    "A75":"Castleblaney",	
    "F45":"Castlerea",	
    "H12":"Cavan",	
    "P56":"Charleville",	
    "F12":"Claremorris",	
    "H71":"Clifden",	
    "P85":"Clonakilty",	
    "H23":"Clones",	
    "E91":"Clonmel",	
    "P24":"Cobh",	
    "H16":"Cootehill",	
    "T12":"Cork City (city centre and southside), Passage West, Cork Airport",	
    "T23":"Cork City (northside), Blarney",	
    "P14":"Cork, Crookstown",	
    "P32":"Cork, Donoughmore",	
    "P47":"Cork, Dunmanway",	
    "T56":"Cork, Watergrasshill",	
    "T34":"Cork, Whitechurch",	
    "R56":"Curragh Camp",	
    "A63":"Delgany",	
    "F94":"Donegal",	
    "A92":"Drogheda",	
    "D01":"Dublin 1",
    "D02":"Dublin 2",
    "D03":"Dublin 3",
    "D04":"Dublin 4",
    "D05":"Dublin 5",
    "D06":"Dublin 6",
    "D6W":"Dublin 6 West",
    "D07":"Dublin 7",
    "D08":"Dublin 8",
    "D09":"Dublin 9",
    "D10":"Dublin 10",
    "D11":"Dublin 11",
    "D12":"Dublin 12",
    "D13":"Dublin 13",
    "D14":"Dublin 14",
    "D15":"Dublin 15",
    "D16":"Dublin 16",
    "D17":"Dublin 17",
    "D18":"Dublin 18",
    "D20":"Dublin 20",
    "D22":"Dublin 22",
    "D24":"Dublin 24",
    "A86":"Dunboyne",	
    "A91":"Dundalk",	
    "X35":"Dungarvan",	
    "A85":"Dunshaughlin",	
    "R45":"Edenderry",	
    "A83":"Enfield",	
    "V95":"Ennis",	
    "Y21":"Enniscorthy",	
    "P61":"Fermoy",	
    "H91":"Galway",	
    "A42":"Garristown",	
    "A96":"Glenageary",	
    "Y25":"Gorey",	
    "A63":"Greystones",	
    "A82":"Kells",	
    "A63":"Kilcoole",	
    "R51":"Kildare",	
    "R95":"Kilkenny",	
    "V93":"Killarney",	
    "X42":"Kilmacthomas",	
    "V35":"Kilmallock",	
    "V15":"Kilrush",	
    "A82":"Kingscourt",	
    "P17":"Kinsale",	
    "A92":"Laytown-Bettystown-Mornington",	
    "F92":"Letterkenny",	
    "F93":"Lifford",	
    "V94":"Limerick",	
    "V31":"Listowel",	
    "T45":"Little Island",	
    "N39":"Longford",	
    "H62":"Loughrea",	
    "K78":"Lucan",	
    "K45":"Lusk",	
    "P12":"Macroom",	
    "K36":"Malahide",	
    "P51":"Mallow",	
    "W23":"Maynooth",	
    "P25":"Midleton",	
    "P67":"Mitchelstown",	
    "H18":"Monaghan",	
    "W34":"Monasterevin",	
    "A94":"Monkstown",	
    "R21":"Muine Bheag",
    "N91":"Mullingar",	
    "W91":"Naas",	
    "C15":"Navan",	
    "E45":"Nenagh",	
    "Y34":"New Ross",	
    "W12":"Newbridge",	
    "A63":"Newcastle",	
    "V42":"Newcastle West",	
    "A63":"Newtownmountkennedy",	
    "A45":"Oldtown",	
    "R32":"Portlaoise",	
    "A67":"Rathnew",	
    "A85":"Ratoath",	
    "R42":"Roscommon",	
    "E53":"Roscrea",	
    "K56":"Rush",	
    "V14":"Shannon",	
    "K34":"Skerries",	
    "P81":"Skibbereen",	
    "F91":"Sligo",	
    "A83":"Summerhill",	
    "K67":"Swords and Dublin Airport",	
    "E41":"Thurles",	
    "E34":"Tipperary",	
    "V92":"Tralee",	
    "H54":"Tuam",	
    "R35":"Tullamore",	
    "A82":"Virginia",	
    "X91":"Waterford",	
    "F28":"Westport",	
    "Y35":"Wexford",	
    "A67":"Wicklow",	
    "P36":"Youghal"
    }
    