name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
            - { os: windows-latest, node: "16.x" }
            - { os: macOS-latest, node: "16.x" }
            - { os: ubuntu-latest, node: "18.x" }
            - { os: ubuntu-latest, node: "16.x" }

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.config.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.config.node }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test